apiVersion: v1
kind: Pod
metadata:
  name: libvirt-scdhcp
  labels:
    app: libvirt-scdhcp
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: libvirt-scdhcp
    image: vladikr/libvirt-scdhcp
    securityContext:
      privileged: true
      runAsUser: 0
    env:
    - name: MODE
      value: proxy
    volumeMounts:
      - mountPath: /host-dev
        name: host-dev
      - mountPath: /host-sys
        name: host-sys
  restartPolicy: Never
  volumes:
  - name: host-dev
    hostPath:
      path: /dev
  - name: host-sys
    hostPath:
      path: /sys
---
